module.exports = () => {
  console.log("\x1b[31m%s\x1b[0m", "         █████  ███████ ███    ███  █████  ██████            ");
  console.log("\x1b[31m%s\x1b[0m", "        ██   ██ ██      ████  ████ ██   ██ ██   ██           ");
  console.log("\x1b[31m%s\x1b[0m", "        ███████ ███████ ██ ████ ██ ███████ ██████            ");
  console.log("\x1b[31m%s\x1b[0m", "        ██   ██      ██ ██  ██  ██ ██   ██ ██   ██           ");
  console.log("\x1b[31m%s\x1b[0m", "        ██   ██ ███████ ██      ██ ██   ██ ██   ██           ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[31m%s\x1b[0m", "         ██   ██  █████  ██████  ██████  ██    ██            ");
  console.log("\x1b[31m%s\x1b[0m", "         ██   ██ ██   ██ ██   ██ ██   ██  ██  ██             ");
  console.log("\x1b[31m%s\x1b[0m", "         ███████ ███████ ██████  ██████    ████              ");
  console.log("\x1b[31m%s\x1b[0m", "         ██   ██ ██   ██ ██      ██         ██               ");
  console.log("\x1b[31m%s\x1b[0m", "         ██   ██ ██   ██ ██      ██         ██               ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[31m%s\x1b[0m", "██████  ██ ██████  ████████ ██   ██ ██████   █████  ██    ██ ");
  console.log("\x1b[31m%s\x1b[0m", "██   ██ ██ ██   ██    ██    ██   ██ ██   ██ ██   ██  ██  ██  ");
  console.log("\x1b[31m%s\x1b[0m", "██████  ██ ██████     ██    ███████ ██   ██ ███████   ████   ");
  console.log("\x1b[31m%s\x1b[0m", "██   ██ ██ ██   ██    ██    ██   ██ ██   ██ ██   ██    ██    ");
  console.log("\x1b[31m%s\x1b[0m", "██████  ██ ██   ██    ██    ██   ██ ██████  ██   ██    ██    ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[31m%s\x1b[0m", "                                                             ");
  console.log("\x1b[34m%s\x1b[0m", "                Ən xoş arzu və diləklərlə!                   ");
};                                              