module.exports = () => {
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "               █████  ███████ ███    ███  █████  ██████            ");
  console.log("\x1b[32m%s\x1b[0m", "              ██   ██ ██      ████  ████ ██   ██ ██   ██           ");
  console.log("\x1b[32m%s\x1b[0m", "              ███████ ███████ ██ ████ ██ ███████ ██████            ");
  console.log("\x1b[32m%s\x1b[0m", "              ██   ██      ██ ██  ██  ██ ██   ██ ██   ██           ");
  console.log("\x1b[32m%s\x1b[0m", "              ██   ██ ███████ ██      ██ ██   ██ ██   ██           ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "               ██   ██  █████  ██████  ██████  ██    ██            ");
  console.log("\x1b[32m%s\x1b[0m", "               ██   ██ ██   ██ ██   ██ ██   ██  ██  ██             ");
  console.log("\x1b[32m%s\x1b[0m", "               ███████ ███████ ██████  ██████    ████              ");
  console.log("\x1b[32m%s\x1b[0m", "               ██   ██ ██   ██ ██      ██         ██               ");
  console.log("\x1b[32m%s\x1b[0m", "               ██   ██ ██   ██ ██      ██         ██               ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "      ██████  ██ ██████  ████████ ██   ██ ██████   █████  ██    ██ ");
  console.log("\x1b[32m%s\x1b[0m", "      ██   ██ ██ ██   ██    ██    ██   ██ ██   ██ ██   ██  ██  ██  ");
  console.log("\x1b[32m%s\x1b[0m", "      ██████  ██ ██████     ██    ███████ ██   ██ ███████   ████   ");
  console.log("\x1b[32m%s\x1b[0m", "      ██   ██ ██ ██   ██    ██    ██   ██ ██   ██ ██   ██    ██    ");
  console.log("\x1b[32m%s\x1b[0m", "      ██████  ██ ██   ██    ██    ██   ██ ██████  ██   ██    ██    ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                              Təbriklər!                           ");
  console.log("\x1b[36m%s\x1b[0m", "                      Ən xoş arzu və diləklərlə!                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
  console.log("\x1b[32m%s\x1b[0m", "                                                                   ");
};                                              